In [1]:
import numpy as np

In [7]:
a = [1,2,3]
a_array = np.array([a])
a_array
a_array.dtype

dtype('int64')

In [5]:
a = [1,2.0,3]
a_array = np.array([a])
a_array
a_array.dtype

dtype('float64')

In [8]:
a_array

array([[1, 2, 3]])

In [9]:
a_array = np.array(a)
a_array.ndim

1

In [12]:
a = [[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array.ndim
a_array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a_array.shape

(2, 3)

In [13]:
a_array[r,c]

NameError: name 'r' is not defined

In [14]:
a_array[0,0]

1

In [15]:
a_array[1,1]

5

In [16]:
a_array[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [18]:
a_array[1,2]

6

In [19]:
a_array[1,2]=11

In [20]:
a_array

array([[ 1,  2,  3],
       [ 4,  5, 11]])

In [21]:
a_array[0:2,1:3]=[[9,10],[8,6]]

In [22]:
a_array

array([[ 1,  9, 10],
       [ 4,  8,  6]])

In [27]:
# initialize arrays
a_array=np.zeros(5,dtype='int32')
a_array

array([0, 0, 0, 0, 0], dtype=int32)

In [28]:
a_array=np.zeros((3,2),dtype='int32')
a_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [29]:
a_array=np.ones((3,2),dtype='int32')
a_array

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [30]:
a_array=np.full((3,2),10)
a_array

array([[10, 10],
       [10, 10],
       [10, 10]])

In [31]:
# array of decimal random values
a_array=np.random.rand(2,3)
a_array

array([[0.26694683, 0.36998036, 0.41453089],
       [0.05464589, 0.86644272, 0.25386557]])

In [32]:
# array of identity matrix
a_array=np.identity(5)
a_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a = [[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array.ndim
a_array

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a_array<3

array([[ True,  True, False],
       [False, False, False]])

In [38]:
a_array[a_array<3]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()