In [4]:
myList=[10,20,30,40,True,False,8.10]
myList.append([50])


In [5]:
myList

[10, 20, 30, 40, True, False, 8.1, [50]]

In [6]:
myList.reverse()

In [7]:
myList

[[50], 8.1, False, True, 40, 30, 20, 10]

In [10]:
myList[]

[10]

In [20]:
myList=[10,20,30,40,True,False,8.10]
myList1.extend([50,60]) 
[10, 20, 30, 40, True, False, 8.1, 50, 60]
myList1=[10,20,30,40,True,False,8.10]
myList
myList.append([50,60]) 
myList1.extend([50,60]) 

myList
myList1


[10, 20, 30, 40, True, False, 8.1, 50, 60]

In [21]:
myList=[10,20,30,40,True,False,8.10]


In [22]:
myList

[10, 20, 30, 40, True, False, 8.1]

In [23]:
myList[::-1]

[8.1, False, True, 40, 30, 20, 10]

In [24]:
import numpy as np

In [28]:
a=np.arange(2,11,1)

In [29]:
np.reshape(a,(3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [33]:
y=[]
a=int(input("Enter Size of Array"))
for i in range(a):
    x=int(input("element"))
    y.append(x)
print("original array is :",y)
z=np.array(y,dtype=float)
print("converted array is:",z)

Enter Size of Array5
element1
element2
element3
element4
element5
original array is : [1, 2, 3, 4, 5]
converted array is: [1. 2. 3. 4. 5.]


In [39]:
x=[10,20,30]
x=np.append(x,[[40,50,60],[70,80,90]])

In [40]:
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
np.reshape(x,(3,3))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [49]:
x=np.array([10,20,30])
y=np.array([40,50,60])
z=np.add(x,y)
z

array([50, 70, 90])

In [51]:
a=np.arange(10,91,10)

In [52]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
b=np.reshape(a,(3,3))

In [55]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [58]:
b[0,:]

array([10, 20, 30])

In [66]:
b[1,1]

50

In [67]:
def add1(c,d):
    z=np.add(c,d)
    return z
c=np.array([1,2,3])
d=np.array([4,5,6])

print(add1(c,d))

[5 7 9]
