In [2]:
import numpy as np

In [8]:
ar1 = np.array([1,2,3,5])

# print(arr)

In [13]:
ar2=np.array([1, 2, 3, 5])

In [16]:
ar2=np.array([1,2,3,'5'])

In [17]:
ar2

array(['1', '2', '3', '5'], dtype='<U11')

In [18]:
ar3=np.array([[1,2,3],[4,5,6]])

In [19]:
ar3

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(ar3)

[[1 2 3]
 [4 5 6]]


In [21]:
ar3.shape

(2, 3)

In [22]:
ar3.any

<function ndarray.any>

#### 

In [25]:
ar4=np.zeros((4,5))

In [26]:
print(ar4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
np.full([4,5],2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [28]:
np.arange(10,25,4)

array([10, 14, 18, 22])

In [32]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [33]:
np.linspace(10,20,6)

array([10., 12., 14., 16., 18., 20.])

In [34]:
np.random.random([4,5]) # random numnbers between 0 and 1

array([[0.02009298, 0.93828871, 0.2398915 , 0.69167374, 0.21470604],
       [0.42730543, 0.64419665, 0.75420049, 0.0739001 , 0.38347734],
       [0.8271079 , 0.6515355 , 0.37480523, 0.99975772, 0.82556854],
       [0.79464164, 0.14585364, 0.6886466 , 0.3682116 , 0.5766445 ]])

In [35]:
ar4.size

20

In [36]:
ar5=np.array([[1,2,3,4],[5,5,7,8],[9,10,11,12]])

In [37]:
ar5

array([[ 1,  2,  3,  4],
       [ 5,  5,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
ar5.size

12

In [40]:
ar5.shape = (4,3) # Array reshaping

In [41]:
ar5

array([[ 1,  2,  3],
       [ 4,  5,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
ar5.size

12

In [47]:
np.sum([[0,1],[0,5]],axis=0) # row level addition : 
#[0,1] 
#[0,5] = 0+0=0 and 1+5 =6 so op os 0,6

array([0, 6])

In [48]:
np.sum([[0,1],[0,5]],axis=1) # column level addition
# [0,1]
# [0,5] 0+1 =1 and 0+5 =5 so op os 1,5

array([1, 5])

In [55]:
a=20
b=10


In [51]:
np.sum([a,b])

30

In [52]:
np.substract([a,b])

AttributeError: module 'numpy' has no attribute 'substract'

In [57]:
np.subtract([a,b])

ValueError: invalid number of arguments

In [58]:
np.sqrt(a)

4.47213595499958

In [59]:
np.exp(b)

22026.465794806718

In [60]:
a=[1,2,4]
b=[2,4,4]
c=[1,2,4]

In [61]:
np.equal(a,b)

array([False, False,  True])

In [62]:
np.equal(a,c)

array([ True,  True,  True])

In [63]:
np.array_equal(a,c)

True

In [64]:
np.sum([a])

7

In [65]:
np.min(a)

1

In [66]:
np.max(a)

4

In [67]:
np.mean(a)

2.3333333333333335

In [68]:
np.median(a)

2.0

In [69]:
a=([1,3,5,7,8,9])

In [70]:
np.median(a)

6.0